version: '3.9'

services:
  next-terminal:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: next-terminal
    restart: unless-stopped
    ports:
      - '8088:8088'
      - '2022:2022'
      - '4822:4822'
    volumes:
      - next-terminal-recording:/usr/local/next-terminal/data/recording
      - next-terminal-drive:/usr/local/next-terminal/data/drive
      - next-terminal-sqlite:/usr/local/next-terminal/data/sqlite
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8088/healthz || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  next-terminal-recording:
  next-terminal-drive:
  next-terminal-sqlite:

